[book]
authors = ["Piotr Kaminski", "John Vanderzyden"]
language = "en"
multilingual = false
src = "docs"
title = "Reviewable User Manual"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/Reviewable/Reviewable"

[preprocessor.classy]
command = "bin/mdbook-classy"
