name: Add all issues to Task Central project

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_token: ${{ secrets.ORGANIZATION_PROJECT_TOKEN }}
          organization: reviewable
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
